### ISSUE TITLE
Setting as default launcher

### ISSUE THREAD

**Issue by Pantyhose-X** [FossifyOrg/App-Launcher#4]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/App-Launcher/issues) or [closed](https://github.com/FossifyOrg/App-Launcher/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/App-Launcher/discussions) or [closed](https://github.com/FossifyOrg/App-Launcher/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/App-Launcher/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Here's what you need to do.
### No need to slide the screen up, Go to app list, App-Launcher itself is the home screen.
1. Setting as default launcher
2. Show all apps icons No need to add them one by one.
3. Managing hidden icons
4. app Drawer No need to move apps one by one to the home screen. 
# 4 app Drawer, Use the application drawer here

<img alt="Screenshot_20240317-105652" src="https://github.com/FossifyOrg/Launcher/assets/42504385/601865d8-8c68-4e82-8cf9-6335318cb10d" width=180 />

<img alt="Screenshot_20240317-105652" src="https://github.com/FossifyOrg/Launcher/assets/42504385/b97f0c7b-d34a-4471-9af8-d40f4c109716" width=180 />

### Why do you want this feature?

app Drawer No need to move apps one by one to the home screen. 
Saving screen space

**Comment by Aga-C** [comment]
App Launcher isn't a real launcher app. It's just a drawer for the apps, so it's not possible.
